version: "3.0"
services: 
  db:
    image: mysql:8
    container_name: safepoint_DB
    environment: 
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: saferoute
      MYSQL_PASSWORD: saferoutepw
      MYSQL_DATABASE: safepoint
    ports: 
      - 3307:3306
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    volumes:
          - /Users/Shared/data/mysql-test:/var/lib/mysql
    restart: always
  app:
    build: .
    container_name: Routing_Server_NodeJS
    image: routing_server:latest
    ports: 
      - "9001:9001"
    environment:
      NODE_ENV: localhost
    volumes:
      - /source:/source
      - /source/node_modules
    restart: always